---
- name: Check if composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_stat
  changed_when: false

- name: Download Composer installer
  get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: "/usr/local/bin/composer"
  when: composer_stat.stat.exists == false and composer_version != "latest"

- name: Download Composer installer
  get_url:
    url: "https://getcomposer.org/composer.phar"
    dest: "/usr/local/bin/composer"
  when: composer_stat.stat.exists == false and composer_version == "latest"

- name: Set composer executable mode
  file:
    path: "/usr/local/bin/composer"
    mode: 0755
